:connect TS-DB1\Inst2

USE [PARE]
GO

ALTER DATABASE [PARE] SET SINGLE_USER WITH ROLLBACK IMMEDIATE 
ALTER DATABASE [PARE] SET NEW_BROKER
ALTER DATABASE [PARE] SET MULTI_USER
Go

:connect TS-DB1\Inst3

USE [Notification]
Go

ALTER DATABASE [Notification] SET SINGLE_USER WITH ROLLBACK IMMEDIATE 
ALTER DATABASE [Notification] SET NEW_BROKER
ALTER DATABASE [Notification] SET MULTI_USER
GO

:connect TS-DB2\Inst2

USE [PCS]
GO

ALTER DATABASE [PCS] SET SINGLE_USER WITH ROLLBACK IMMEDIATE 
ALTER DATABASE [PCS] SET NEW_BROKER
ALTER DATABASE [PCS] SET MULTI_USER
GO